name: Auctioneer
version: '${version}'
main: com.anotherpillow.auctioneer.Auctioneer
api-version: '1.19'

commands:
  auctioneer:
    description: Provides info on plugin.
    usage: /auctioneer
  increment:
    description: tester
    usage: /increment
  startbidding:
    description: Start an auction on held item.
    usage: /startbidding
  startbids:
    description: Start an auction on held item.
    usage: /startbids
  upauction:
    description: Start an auction on held item.
    usage: /upauction
  viewauction:
    description: View/bid on an auction.
    usage: /viewauction <uuid>
  openauction:
    description: View/bid on an auction.
    usage: /viewauction <uuid>
  bid:
    description: View/bid on an auction.
    usage: /viewauction <uuid>